import Footer from '@/components/shared/footer';
import Navbar from '@/components/shared/navbar';
import './globals.css';

export const metadata = {
  title: 'Flexibble',
  description: 'Generated by farhan ahmed nahid',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='utf-8' />

        <link rel='icon' href='/favicon.ico' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </head>
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
